name: remote ssh commands

on:
  push:
    branches:
      - master

jobs:
  build:
   name: build
   runs-on: ubuntu-latest

   steps:
     - name: executing remote ssh commands using passward
       uses: appleboy/ssh-action@v1
       with:
         host: ${{ secrets.HOST}}
         username: ${{ secrets.USERNAME}}
         password: ${{ secrets.PASSWORD}}
         port: ${{ secrets.PORT}}
         script: |
           cd j-app 
           docker stop jen
           docker rm jen
           docker build -t jen .
           docker run --name jen -d -p 8000:8000 jen
           
